apiVersion: v1
kind: Secret
metadata:
  name: secret-group-18-fastfood-backend
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "foobarbaz"
  PGADMIN_DEFAULT_EMAIL: "tech@mail.com"
  PGADMIN_DEFAULT_PASSWORD: "123456"